server:
  port: ${PORT:8080}

spring:
  application:
    name: monolito
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    properties:
      hibernate:
        show_sql: true
        format_sql: true

