server:
  port: ${PORT:8081}

spring:
  application:
    name: monolito
  datasource:
    url: ${DB_URL:jdbc:tc:postgresql:latest:///integration-tests-db}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

